spring:
  application:
    name: spring-java
  datasource:
    url: jdbc:mysql://localhost:3306/shopdevgo
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8000

# Cấu hình logging cho Hibernate
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG  # Hiển thị câu lệnh SQL
        orm.jdbc.bind: TRACE  # Hiển thị tham số được truyền vào câu lệnh SQL

